### ISSUE TITLE
Swift 3.0 Support

### ISSUE THREAD

**Issue by maheshbabu159** [bitly/bitly_ios_sdk_release#1]
Unable to use with latest swift 3.0.
Could you please suggest, how to use with swift 3.0.

ld: /Users/maheshbabusomineni/Desktop/Sample/Pods/BitlySDK/BitlySDK.framework/BitlySDK **compiled with older version of Swift language (2.0) than previous files (3.0) for architecture x86_64**
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by jctbitly** [comment]
We are working on a release that will resolve this issue.

**Comment by jctbitly** [comment]
The latest version (0.5.0) supports Swift 3.
