### ISSUE TITLE
Fix Carthage download of version 1.0.3

### ISSUE THREAD

**Issue by jose-ibanez** [bitly/bitly_ios_sdk_release#3]
Please add BitlySDK.framework.zip to the assets in the 1.0.3 release to fix the download-only build via Carthage.

When my Cartfile.resolved contains
`github "bitly/bitly_ios_sdk_release" "1.0.0"`

I see the following:
```
$ carthage bootstrap 
*** Downloading bitly_ios_sdk_release.framework binary at "1.0.0"
```

However when my Cartfile.resolved contains
`github "bitly/bitly_ios_sdk_release" "1.0.3"`

I see the following:
```
$ carthage bootstrap
*** Checking out bitly_ios_sdk_release at "1.0.3"
*** xcodebuild output can be found in /var/folders/bb/fszzx_1d4yq8bldr376rf2vw0000gn/T/carthage-xcodebuild.3Ldf86.log
*** Skipped building bitly_ios_sdk_release due to the error:
Dependency "bitly_ios_sdk_release" has no shared framework schemes
If you believe this to be an error, please file an issue with the maintainers at https://github.com/bitly/bitly_ios_sdk_release/issues/new
```

I believe this is because Carthage specifically looks for a zip file attached to the release when downloading pre-built frameworks. The 1.0.0 release has BitlySDK.framework.zip alongside the source code, while the 1.0.3 release does not.

Thanks!
(edited to fix my broken markdown)

**Comment by jctbitly** [comment]
This should be fixed now.
